### ISSUE TITLE
async.js shouldn't be in the middleware folder

### ISSUE THREAD

**Issue by dexbyte** [bradtraversy/devcamper-api#17]
I think `asyncHandler` function shound't be inside `middleware` folder but somewhere else, like in the `untils` folder as it is not being used by `express.use()`, the way we use any express middleware, so the untils directory would be more appropriate.

This is just my opinion, I don't know if I am missing something. Any thoughts?

**Comment by kirasiris** [comment]
Please avoid posting issues relevant to files structures; everyone has different tastes/opinions and arguing about it can become a hot topic to some developers.
