### ISSUE TITLE
Postman returning a empty array - Problem solved

### ISSUE THREAD

**Issue by marcusungarette** [bradtraversy/devcamper-api#7]
When lesson 21. starts you forgot to call 

const mongoose = require("mongoose");

inside controllers/bootcamps.js

Without this const, the Postman was returning me an empty array.

**Comment by samsam1414** [comment]
In Video 21, go to @3:00. Brad starts to type `const mongoose = require('mongoose');` there.

https://www.udemy.com/course/nodejs-api-masterclass/learn/lecture/16581768

**Comment by marcusungarette** [comment]
he did inside models/bootcamp.js, not inside controllers/bootcamps.js

**Comment by samsam1414** [comment]
I see.

But why do you need `mongoose` inside of `controllers/bootcamps.js`? Nothing inside of there requires direct access to mongoose.

**Comment by marcusungarette** [comment]
Ok. For me wasn't working fine without
